function gabcd = hrr(RAB,gap1bm1cd,gabm1cd,L1,L2,L3,L4)

%Aug 29th 2017
%The matrices I need should be generated by special contract_vrr and
%contract_ascs functions, because the angular momentum will not be the same
%as in the native integrals.

%This function should handle arbitrary matrices of type
%[DimA,DimB(1,3,6,etc)|DimC,DimD], where DimA, DimC and DimD can be any
%dimension (up to L = 9 or 10).

%This goes with RAB
Term1 = gabm1cd;

%This goes alone, and is reshaped.
Term2 = gap1bm1cd;





end